# Test your FastAPI endpoints

GET http://127.0.0.1:8000/api/productos_por_tipo_y_marca
Accept: application/json

###

GET http://127.0.0.1:8000/api/categorias
Accept: application/json

###

GET http://127.0.0.1:8000/api/categorias/68533cc00eb2af9902428617/materiales
Accept: application/json

###

GET http://127.0.0.1:8000/api/trabajadores
Accept: application/json

###

GET http://127.0.0.1:8000/api/forms
Accept: application/json

###

POST http://127.0.0.1:8000/api/auth/trabajador
Content-Type: application/json

{
    "ci": "12345678",
    "contraseña": "12345678*"
}

###

GET http://127.0.0.1:8000/api/brigadas
Accept: application/json

