# Test your FastAPI endpoints

GET http://127.0.0.1:8000/api/productos_por_tipo_y_marca
Accept: application/json

###

GET http://127.0.0.1:8000/api/categorias
Accept: application/json

###

GET http://127.0.0.1:8000/api/categorias/68533cc00eb2af9902428617/materiales
Accept: application/json

###

GET http://127.0.0.1:8000/api/trabajadores
Accept: application/json

###

GET http://127.0.0.1:8000/api/forms
Accept: application/json

###

POST http://127.0.0.1:8000/api/auth/trabajador
Content-Type: application/json

{
    "ci": "12345678",
    "contraseña": "12345678*"
}

###

GET http://127.0.0.1:8000/api/brigadas
Accept: application/json

### Asignar trabajador existente a brigada
POST http://127.0.0.1:8000/api/brigadas/685aa9ff1823a41af64b1628/trabajadores
Content-Type: application/json

{
  "nombre": "Patricia Herrera",
  "CI": "22334455"
}

### Crear trabajador y asignarlo a brigada
POST http://127.0.0.1:8000/api/trabajadores/asignar_brigada
Content-Type: application/json

{
  "ci": "123456789012",
  "nombre": "Jude Bellingham",
  "brigada_id": "6865f9d13ec25099449b4a00",
  "contrasena": "heyjude"
}

### Test: Materiales usados por una brigada (sin filtro de categoria)
GET http://localhost:8000/api/reportes/materiales-usados/brigada?lider_ci=02091968281&fecha_inicio=2025-01-01&fecha_fin=2025-12-31
Accept: application/json

### Test: Materiales usados por una brigada (con filtro de categoria)
GET http://localhost:8000/reportes/materiales-usados/brigada?lider_ci=12345678&fecha_inicio=2024-01-01&fecha_fin=2024-12-31&categoria=Cemento
Accept: application/json

### Test: Materiales usados por todas las brigadas (sin filtro de categoria)
GET http://localhost:8000/api/reportes/materiales-usados/todas-brigadas?fecha_inicio=2025-01-01&fecha_fin=2025-12-31
Accept: application/json

### Test: Materiales usados por todas las brigadas (con filtro de categoria)
GET http://localhost:8000/reportes/materiales-usados/todas-brigadas?fecha_inicio=2024-01-01&fecha_fin=2024-12-31&categoria=Cemento
Accept: application/json

### Eliminar contraseña de un trabajador (dejar de ser jefe)
DELETE http://127.0.0.1:8000/api/trabajadores/03111866789/contrasena
Accept: application/json