[phases.setup]
aptPkgs = [
  "libcairo2-dev",
  "pkg-config",
  "python3-dev",
  "libjpeg-dev",
  "zlib1g-dev",
  "libfreetype6-dev",
  "libffi-dev",
  "libxcb1-dev",
  "libx11-dev",
  "libxcb-render0-dev",
  "libxcb-shm0-dev",
  "libx11-xcb-dev",
  "libxcb-xkb-dev",       # <--- importante
  "libxkbcommon-x11-dev", # <--- importante
  "libxkbcommon-dev",     # <--- soporte de teclados
]