[phases.setup]
aptPkgs = [
  "libcairo2-dev",      # Cairo
  "pkg-config",
  "python3-dev",
  "libjpeg-dev",
  "zlib1g-dev",
  "libfreetype6-dev",
  "libffi-dev",
  "libxcb1-dev",        # XCB base
  "libx11-dev",         # X11 base
  "libxcb-render0-dev", # XCB render extension
  "libxcb-shm0-dev"     # XCB shared memory extension
]